/**
 * @file        Item.h
 * @brief       Item entity declaration.
 * @details     Declares the Item class, which represents a single named
 *              inventory entry with an associated integer quantity.
 *
 * @author      Seth Laurie
 * @date        2026-05-15
 * @version     1.0.0
 *
 * @copyright   Copyright (c) 2026. All rights reserved.
 *
 * @par Revision History:
 * | Version | Date       | Author      | Description     |
 * |---------|------------|-------------|-----------------|
 * | 1.0.0   | 2026-05-15 | Seth Laurie | Initial release |
 *
 * @par Safety Classification:
 * Evaluation / non-production component. Must be formally reclassified as
 * IEC 62304 Class A, B, or C before integration into a regulated medical
 * device. All changes require documented change control.
 *
 * @par Applicable Standards:
 * - IEC 62304: Medical device software – Software life cycle processes
 * - ISO 14971: Medical devices – Application of risk management to medical devices
 * - MISRA C++ 2008: Guidelines for the use of the C++ language in critical systems
 */

#pragma once

#include <string>

namespace eval {

/**
 * @class   Item
 * @brief   Represents a single inventory item identified by a unique name.
 *
 * @details An Item pairs a human-readable name with a signed integer
 *          quantity. The quantity may be adjusted incrementally via
 *          adjustQuantity(). The class provides value semantics; copy and
 *          move operations are implicitly generated by the compiler.
 *
 * @invariant getName() returns a non-empty string after construction.
 * @invariant getQuantity() reflects the sum of all prior adjustQuantity()
 *            calls applied to the initial quantity supplied at construction.
 */
class Item
{
public:
    // -----------------------------------------------------------------------
    // Construction / destruction
    // -----------------------------------------------------------------------

    /**
     * @brief   Constructs an Item with the given name and initial quantity.
     * @param   name      Human-readable item identifier. Must not be empty.
     * @param   quantity  Starting stock count (may be zero or negative).
     */
    Item(std::string name, int quantity);

    // Compiler-generated copy, move, and destructor are sufficient.
    Item(const Item&)            = default;
    Item(Item&&)                 = default;
    Item& operator=(const Item&) = default;
    Item& operator=(Item&&)      = default;
    ~Item()                      = default;

    // -----------------------------------------------------------------------
    // Accessors
    // -----------------------------------------------------------------------

    /**
     * @brief   Returns the item's name.
     * @return  Const reference to the internal name string.
     */
    [[nodiscard]] const std::string& getName() const noexcept;

    /**
     * @brief   Returns the current quantity.
     * @return  Current stock count.
     */
    [[nodiscard]] int getQuantity() const noexcept;

    // -----------------------------------------------------------------------
    // Mutators
    // -----------------------------------------------------------------------

    /**
     * @brief   Adjusts the quantity by a signed delta.
     * @param   delta  Amount to add (positive) or subtract (negative).
     * @note    No overflow or domain checking is performed. Callers are
     *          responsible for ensuring the result remains semantically valid.
     */
    void adjustQuantity(int delta) noexcept;

private:
    std::string m_name;     ///< Human-readable identifier; immutable after construction.
    int         m_quantity; ///< Current stock count; modified via adjustQuantity().
};

} // namespace eval
